# docker compose versions
version: '2'

# shared volumes
volumes:
  project:

services:

  # mongodb
  mongo:
    image: mongo

  # web app bundle build
  app:
    image: my_app
    volumes:
      - project:/srv/crn-app/dist
    env_file: ./config.env

  # crn core (bids-core)
  core:
    image: my_bids
    volumes:
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
    env_file: ./config.env
    restart: always

  # crn node server
  server:
    image: my_server
    volumes:
      - ./server/client.config.js:/srv/crn-server/client.config.js:rw
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/srv/crn-server/persistent
    env_file: ./config.env
    restart: always

  # sftp access
  sftp:
    image: atmoz/sftp
    volumes:
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/home/${SFTP_USER}/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/home/${SFTP_USER}/srv/crn-server/persistent
      - /home/${SFTP_USER}/.ssh/keys:/home/${SFTP_USER}/.ssh/keys
    ports:
      - "8111:22"
    command: ${SFTP_USER}::1001

  # nginx - static file serving and service proxy
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - project:/srv/crn-app/dist
    ports:
      - "80:80"
      - "8110:8110"
      - "443:443"
    depends_on:
      - server
      - core
